version: '3'

services:
  audio-app:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./audio_processing.db:/app/audio_processing.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/jobs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  output:
  logs: 